INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Schedule A', null, 34, 0, 0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Real Estate', 1, 3, 0, 0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Real Estate Agent', 2, 0, 0, 0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Real Estate Developer', 2, 0, 0, 0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Property Management',2,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Shipping Agency',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Shipping Business',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Tourism',1,8,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Commercial Traveller',8,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Clearing and Forwarding / Freight Forwarders',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Insurance',1,3,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Insurance and Assurance',11,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Insurance Broker',11,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Re-Insurance',11,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Tourist Hotels, Lodges or Camps',8,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Tour Operator',8,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Professional Hunting',8,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Travel Agent',8,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Car Hire',8,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Tourist Photography',8,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Tourist Promotion',8,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Banking & Financial Services',1,4,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Banking & Financial Institutions',22,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Capital Market & Credit Card Management',22,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Stock Exchange',22,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Stock Exchange Brokers',22,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Transportation of Passengers or Goods by Air',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Postal Services',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Transportation of Passengers or Goods by Rail',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Telecommunication',1,4,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Internet Service Provider',30,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Internet Cafe',30,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Telecommunication Services',30,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Sale of Telecommunication Equipment',30,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Cargo Valuation',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Cargo Superintendence and Pre-shipment Inspection',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Cargo Tallying',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Harbours and Cargo Handling',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Electricity Production and Distribution',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Bureau de Change',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Stevedoring or Lighterage',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Courier Services and Mail Agent',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Broadcasting & Television',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Ship Chandlers / Miscellaneous Port Services',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Refining Crude Oil',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Night Clubs',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Dealers in Arms and Ammunition',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Dealers in Explosives',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Social Security Provider',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Export and Selling',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Water Drilling and Supply',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Dealers in Broadcasting Apparatus',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Manufacturing and Selling',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Motor Vehicle Dealer',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Commission Agent or Manufacturer''s Representative',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Import and Selling',1,0,0,0);
INSERT INTO categories (name, parent_id, categories_count, licence_applications_count, licences_count) VALUES ('Gold and Silver Smith and Gemstone Dealer',1,0,0,0);