# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "addresses", :force => true do |t|
    t.column "company_id", :integer,               :null => false
    t.column "p_o_box",    :string,  :limit => 10
    t.column "email",      :string,  :limit => 50
    t.column "block",      :string,  :limit => 10
    t.column "house_no",   :string,  :limit => 10
    t.column "plot_no",    :string,  :limit => 10
    t.column "street",     :string,  :limit => 50
    t.column "ward_id",    :integer,               :null => false
    t.column "telephone",  :string,  :limit => 15
    t.column "fax",        :string,  :limit => 15
  end

  add_index "addresses", ["company_id"], :name => "idx_addresses_company"

  create_table "attachments", :force => true do |t|
    t.column "licence_application_id", :integer, :null => false
    t.column "cert_inc_or_reg",        :boolean, :null => false
    t.column "memorandum",             :boolean, :null => false
    t.column "tz_proof",               :boolean, :null => false
    t.column "att_powers",             :boolean, :null => false
    t.column "premises",               :boolean, :null => false
    t.column "tin_cert",               :boolean, :null => false
    t.column "cal",                    :boolean, :null => false
    t.column "tal",                    :boolean, :null => false
    t.column "prof_cert",              :boolean, :null => false
    t.column "air_sea_worth",          :boolean, :null => false
    t.column "other",                  :text
  end

  add_index "attachments", ["licence_application_id"], :name => "idx_attachments_licence_applications"

  create_table "categories", :force => true do |t|
    t.column "name",                       :string,  :limit => 70,                :null => false
    t.column "parent_id",                  :integer
    t.column "categories_count",           :integer,               :default => 0
    t.column "licence_applications_count", :integer,               :default => 0
    t.column "licences_count",             :integer,               :default => 0
  end

  create_table "companies", :force => true do |t|
    t.column "name",            :string,  :limit => 200,                :null => false
    t.column "investment_type", :string,  :limit => 3,                  :null => false
    t.column "business_type",   :string,  :limit => 3,                  :null => false
    t.column "inc_or_reg_no",   :string,  :limit => 15
    t.column "parent_id",       :integer
    t.column "companies_count", :integer,                :default => 0
  end

  add_index "companies", ["investment_type"], :name => "idx_companies_investment_type"
  add_index "companies", ["name"], :name => "idx_companies_name"

  create_table "companies_countries", :id => false, :force => true do |t|
    t.column "company_id", :integer, :null => false
    t.column "country_id", :integer, :null => false
  end

  create_table "countries", :force => true do |t|
    t.column "name", :string, :limit => 50
  end

  create_table "directors", :force => true do |t|
    t.column "company_id", :integer,               :null => false
    t.column "name",       :string,  :limit => 50, :null => false
  end

  add_index "directors", ["company_id"], :name => "idx_directors_company"

  create_table "districts", :force => true do |t|
    t.column "region_id", :integer,               :null => false
    t.column "name",      :string,  :limit => 25, :null => false
  end

  add_index "districts", ["name", "region_id"], :name => "idx_districts_region"

  create_table "licence_applications", :force => true do |t|
    t.column "category_id",       :integer,                                  :null => false
    t.column "user_id",           :integer
    t.column "app_date",          :date,                                     :null => false
    t.column "signed",            :boolean,                                  :null => false
    t.column "processed",         :boolean,               :default => false
    t.column "subsidiary",        :boolean,               :default => false
    t.column "principal_licence", :string,  :limit => 15
    t.column "licence_id",        :integer
    t.column "company_id",        :integer
  end

  add_index "licence_applications", ["app_date", "processed", "category_id"], :name => "idx_licence_applications_processed_app_date_category"

  create_table "licences", :force => true do |t|
    t.column "user_id",         :integer
    t.column "licence_type",    :string,  :limit => 1,  :null => false
    t.column "temp_number",     :string,  :limit => 15
    t.column "temp_issue_date", :date
    t.column "category_id",     :integer
    t.column "perm_number",     :string,  :limit => 15
    t.column "perm_issue_date", :date
  end

  add_index "licences", ["temp_issue_date"], :name => "idx_licences_issue_date"
  add_index "licences", ["temp_number"], :name => "idx_licences_number"

  create_table "regions", :force => true do |t|
    t.column "name", :string, :limit => 25, :null => false
  end

  create_table "roots", :force => true do |t|
    t.column "root_password", :string, :limit => 40
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "tins", :force => true do |t|
    t.column "company_id", :integer,              :null => false
    t.column "tin_number", :string,  :limit => 9, :null => false
  end

  add_index "tins", ["company_id"], :name => "idx_tins_company"

  create_table "users", :force => true do |t|
    t.column "pword",      :string,   :limit => 40, :null => false
    t.column "email",      :string,   :limit => 50, :null => false
    t.column "first_name", :string,   :limit => 20, :null => false
    t.column "surname",    :string,   :limit => 20, :null => false
    t.column "user_type",  :integer,                :null => false
    t.column "created_at", :datetime
  end

  create_table "wards", :force => true do |t|
    t.column "district_id", :integer,               :null => false
    t.column "name",        :string,  :limit => 25, :null => false
  end

end
